describe('template spec', () => {
  it('passes', () => {
    cy.visit('https://africx-admin-test.afric.group/auth/login')
    cy.get('[name="username"]').click();
    cy.get('[name="username"]').type('sibpro61+13@gmail.com');
    cy.get('#input-2').click();
    cy.get('#input-2').type('12092');
    cy.get('#checkbox-4').check();
    cy.get('#app button.v-btn').click();
    cy.get('#app a.bg-primary span.v-btn__content').click();
    cy.get('#v-list-group--id-Symbol\\(68\\) div.mr-auto').click();
    cy.get('#app a[href="/users"] div.v-list-item-title').click();
    cy.get('#app button.bg-primary span.v-btn__content').click();
    cy.get('#v-menu-180 div:nth-child(2) > div.v-list-item__content > div.v-list-item-title').click();
    cy.get('#app button.bg-primary span.v-btn__content').click();
    cy.get('#v-menu-180 div:nth-child(2) > div.v-list-item__content > div.v-list-item-title').click();
    cy.get('#input-511').click();
    cy.get('#input-511').type('qatest@gmail.com');
    cy.get('#app path[d="M14.4,6L14,4H5V21H7V14H12.6L13,16H20V6H14.4Z"]').click();
    cy.get('#v-menu-517 div:nth-child(7) div.v-list-item-title').click();
    cy.get('#app div:nth-child(4) > div:nth-child(1) > div.v-row > div:nth-child(2)').click();
    cy.get('#input-513').click();
    cy.get('#input-513').type('677747490');
    cy.get('#app button.v-btn--variant-tonal').click();
    cy.get('#input-561').click();
    cy.get('#v-menu-563 div:nth-child(2) > div.v-list-item__content > div.v-list-item-title').click();
    cy.get('#input-564').click();
    cy.get('#input-564').type('QA');
    cy.get('#input-566').click();
    cy.get('#input-566').type('TEST');
    cy.get('#input-568').click();
    cy.get('#v-menu-570 div:nth-child(2) > div.v-list-item__content > div.v-list-item-title').click();
    cy.get('#app div.v-field--focused div.v-field__input').click();
    cy.get('#v-menu-573 div:nth-child(2) > div.v-list-item__content > div.v-list-item-title').click();
    cy.get('#app button.v-btn--variant-tonal span.v-btn__content').click();
    cy.get('#input-604').click();
    cy.get('#v-menu-606 button.v-btn--rounded').click();
    cy.get('#v-menu-606 button.v-date-picker-controls__month-btn span.v-btn__content').click();
    cy.get('#v-menu-606 path[d="M7,10L12,15L17,10H7Z"]').click();
    cy.get('#v-menu-606 button:nth-child(74)').click();
    cy.get('#v-menu-606 div:nth-child(32) span.v-btn__content').click();
    cy.get('#input-607').click();
    cy.get('#input-607').type('QA TEST');
    cy.get('#input-609').click();
    cy.get('#v-menu-611 div:nth-child(7)').click();
    cy.get('#input-612').click();
    cy.get('#input-612').type('QA TEST');
    cy.get('#app button.v-btn--variant-tonal span.v-btn__content').click();
    cy.get('#input-859').click();
    cy.get('#v-menu-861 div:nth-child(7) div.v-list-item-title').click();
    cy.get('#input-862').click();
    cy.get('#v-menu-864 div:nth-child(6) div.v-list-item-title').click();
    cy.get('#input-865').click();
    cy.get('#input-865').type('Douala');
    cy.get('#input-867').click();
    cy.get('#app div.v-stepper-window-item.v-window-item--active div.v-row').click();
    cy.get('#input-867').type('AKWA');
    cy.get('#input-869').click();
    cy.get('#input-869').type('BP10029');
    cy.get('#input-871').click();
    cy.get('#input-871').type('QA TEST');
    cy.get('#input-873').click();
    cy.get('#input-873').type('QA TEST');
    cy.get('#input-875').click();
    cy.get('#v-menu-877 div:nth-child(4) div.v-list-item__content div.v-list-item-title').click();
    cy.get('#input-878').click();
    cy.get('#input-878').type('QA TEST');
    cy.get('#app div.v-field--focused div.v-field__input').click();
    cy.get('#v-menu-882 div:nth-child(3) div.v-list-item__content div.v-list-item-title').click();
    cy.get('#app div.v-stepper').click();
    cy.get('#app button.v-btn--variant-tonal').click();
    cy.get('#input-959').click();
    cy.get('#v-menu-961 div:nth-child(2) > div.v-list-item__content > div.v-list-item-title').click();
    cy.get('#input-962').click();
    cy.get('#input-962').type('CE2343343343');
    cy.get('#input-964').click();
    cy.get('#input-964').type('PO634342343434');
    cy.get('#input-966').click();
    cy.get('#input-966').type('QA TEST');
    cy.get('#input-968').click();
    cy.get('#v-menu-970 div:nth-child(7) div.v-list-item-title').click();
    cy.get('#input-971').click();
    cy.get('#input-973').click();
    cy.get('#v-menu-975 div:nth-child(2) > div.v-list-item__content > div.v-list-item-title').click();
    cy.get('#input-976').click();
    cy.get('#v-menu-978 div:nth-child(2) > div.v-list-item__content > div.v-list-item-title').click();
    cy.get('#app div.v-stepper-window-item.v-window-item--active div:nth-child(10)').click();
    cy.get('#input-981').type('QA TEST');
    cy.get('#input-986').click();
    cy.get('#v-menu-988 path[d="M7,10L12,15L17,10H7Z"]').click();
    cy.get('#v-menu-988 button:nth-child(55) span.v-btn__content').click();
    cy.get('#v-menu-988 div:nth-child(17) span.v-btn__content').click();
    cy.get('#input-989').click();
    cy.get('#input-989').type('dOUALA');
    cy.get('#input-991').click();
    cy.get('#v-menu-993 button.v-btn--density-comfortable svg.v-icon__svg').click();
    cy.get('#v-menu-993 button:nth-child(111)').click();
    cy.get('#v-menu-993 div:nth-child(32) button.v-btn').click();
    cy.get('#app div.v-stepper-window-item.v-window-item--active div.v-card-actions div.d-flex button.v-btn span.v-btn__content').click();
    cy.get('#input-1427').click();
    cy.get('#v-menu-1429 div:nth-child(7) div.v-list-item-title').click();
    cy.get('#input-1430').click();
    cy.get('#v-menu-1432 path[d="M7,10L12,15L17,10H7Z"]').click();
    cy.get('#app div.v-stepper-window-item.v-window-item--active div.v-col-md-12 div.v-card div.v-card-actions').click();
    cy.get('#app button.v-btn--variant-tonal span.v-btn__content').click();
    cy.get('#input-1703').check();
    cy.get('#input-1708').check();
    cy.get('#input-1699').check();
    cy.get('#input-1714').check();
    cy.get('#input-1719').check();
    cy.get('#input-1724').check();
    cy.get('#input-1729').check();
    cy.get('#input-1734').check();
    cy.get('#input-1739').check();
    cy.get('#input-1744').check();
    cy.get('#input-1743').check();
    cy.get('#input-1749').check();
    cy.get('#input-1754').check();
    cy.get('#input-1775').check();
    cy.get('#input-1780').check();
    cy.get('#input-1782').click();
    cy.get('#input-1782').type('12092');
    cy.get('#app div:nth-child(19)').click();
    cy.get('#input-1784').click();
    cy.get('#input-1784').type('12092');
    cy.get('#app div.v-stepper-window-item.v-window-item--active div.justify-end.v-card-actions button.v-btn span.v-btn__content').click();
  })
})