describe('template spec', () => {
  it('passes', () => {
    cy.visit('https://africx-admin-test.afric.group/auth/login')
    cy.get('[name="username"]').click();
    cy.get('[name="username"]').type('sibpro61+13@gmail.com');
    cy.get('#input-2').click();
    cy.get('#input-2').type('12092');
    cy.get('#checkbox-4').check();
    cy.get('#app button.v-btn').click();
    cy.get('#app a.bg-primary span.v-btn__content').click();
    cy.get('#v-list-group--id-Symbol\\(68\\) div.mr-auto').click();
    cy.get('#app a[href="/users"] div.v-list-item-title').click();
    cy.get('#app div.vue3-easy-data-table__loading-mask').click();
    cy.get('#app button.bg-primary').click();
    cy.get('#v-menu-177 div.v-list > div:nth-child(1)').click();
    cy.get('#input-509').click();
    cy.get('#input-509').type('qatestingbank@gmail.com');
    cy.get('#input-511').click();
    cy.get('#input-513').click();
    cy.get('#v-menu-515 div:nth-child(7)').click();
    cy.get('#input-511').click();
    cy.get('#input-511').type('656660090');
    cy.get('#app button.v-btn--variant-tonal span.v-btn__content').click();
    cy.get('#input-562').click();
    cy.get('#v-menu-564 div:nth-child(2) > div.v-list-item__content > div.v-list-item-title').click();
    cy.get('#input-565').click();
    cy.get('#input-565').type('QA TEST');
    cy.get('#input-567').click();
    cy.get('#input-567').type('BANK ACCOUNT');
    cy.get('#input-569').click();
    cy.get('#v-menu-571 div:nth-child(3) div.v-list-item__content div.v-list-item-title').click();
    cy.get('#input-572').click();
    cy.get('#v-menu-574 div:nth-child(2) > div.v-list-item__content > div.v-list-item-title').click();
    cy.get('#input-575').click();
    cy.get('#input-575').type('QA TEST');
    cy.get('#input-577').click();
    cy.get('#v-menu-579 div:nth-child(2) > div.v-list-item__content > div.v-list-item-title').click();
    cy.get('#input-577').click();
    cy.get('#v-menu-579 div:nth-child(4) div.v-list-item-title').click();
    cy.get('#app button.v-btn--variant-tonal span.v-btn__content').click();
    cy.get('#input-618').click();
    cy.get('#input-618').type('QA TEST');
    cy.get('#input-620').click();
    cy.get('#input-620').type('QA TEST');
    cy.get('#input-622').click();
    cy.get('#v-menu-624 div:nth-child(4) div.v-list-item__content div.v-list-item-title').click();
    cy.get('#input-625').click();
    cy.get('#input-625').type('QA TEST');
    cy.get('#input-627').click();
    cy.get('#v-menu-629 div:nth-child(8) div.v-list-item-title').click();
    cy.get('#app div.v-stepper-actions').click();
    cy.get('#app button.v-btn--variant-tonal').click();
    cy.get('#input-675').click();
    cy.get('#v-menu-677 div:nth-child(7) div.v-list-item-title').click();
    cy.get('#input-678').click();
    cy.get('#app div.v-field--focused div.v-field__input').click();
    cy.get('#v-menu-680 div:nth-child(6) div.v-list-item-title').click();
    cy.get('#input-681').click();
    cy.get('#input-681').type('DOUALA');
    cy.get('#input-683').click();
    cy.get('#input-683').type('AKWA');
    cy.get('#input-685').click();
    cy.get('#input-685').type('049342');
    cy.get('#input-687').click();
    cy.get('#input-687').type('2234325');
    cy.get('#input-689').click();
    cy.get('#input-689').type('324234');
    cy.get('#input-693').click();
    cy.get('#input-693').type('UBA');
    cy.get('#app button.v-btn--variant-tonal span.v-btn__content').click();
    cy.get('#input-753').check();
    cy.get('#input-754').click();
    cy.get('#v-menu-756 button.v-btn--density-comfortable svg.v-icon__svg').click();
    cy.get('#v-menu-756 button:nth-child(32) span.v-btn__content').click();
    cy.get('#v-menu-756 div:nth-child(40) button.v-btn').click();
    cy.get('#input-757').click();
    cy.get('#input-757').type('DOUALA');
    cy.get('#input-759').click();
    cy.get('#v-menu-761 div:nth-child(7) div.v-list-item-title').click();
    cy.get('#input-762').click();
    cy.get('#v-menu-764 div:nth-child(2) > div.v-list-item__content > div.v-list-item-title').click();
    cy.get('#input-765').click();
    cy.get('#v-menu-767 div:nth-child(2) > div.v-list-item__content > div.v-list-item-title').click();
    cy.get('#input-768').click();
    cy.get('#input-768').type('CE34353465646');
    cy.get('#input-770').click();
    cy.get('#input-770').type('PO4783465734');
    cy.get('#input-772').click();
    cy.get('#v-menu-774 button.v-btn--density-comfortable svg.v-icon__svg').click();
    cy.get('#v-menu-774 button:nth-child(47) span.v-btn__content').click();
    cy.get('#v-menu-774 div:nth-child(33) span.v-btn__content').click();
    cy.get('#input-775').click();
    cy.get('#input-775').type('JSBDFHFI4R4');
    cy.get('#input-777').click();
    cy.get('#v-menu-779 button.v-btn--density-comfortable svg.v-icon__svg').click();
    cy.get('#v-menu-779 button:nth-child(110)').click();
    cy.get('#v-menu-779 div:nth-child(25) span.v-btn__content').click();
    cy.get('#app button.v-btn--variant-tonal span.v-btn__content').click();
    cy.get('#input-1384').check();
    cy.get('#input-1388').check();
    cy.get('#input-1393').check();
    cy.get('#input-1399').check();
    cy.get('#input-1404').check();
    cy.get('#input-1409').check();
    cy.get('#input-1414').check();
    cy.get('#input-1419').check();
    cy.get('#input-1424').check();
    cy.get('#input-1428').check();
    cy.get('#app label[for="input-1434"] div').click();
    cy.get('#input-1434').check();
    cy.get('#input-1439').check();
    cy.get('#app div:nth-child(15) > div.v-card > div.v-card-actions > div.d-flex > button.v-btn > span.v-btn__content').click();
    cy.get('#input-1475').click();
    cy.get('#input-1475').type('QA TEST');
    cy.get('#app div.v-field--focused div.v-field__input').click();
    cy.get('#v-menu-1479 div:nth-child(7)').click();
    cy.get('#input-1480').click();
    cy.get('#input-1480').type('690009000');
    cy.get('#app div:nth-child(15) > div.v-card > div.v-card-actions > div.d-flex > button.v-btn').click();
    cy.get('#input-1550').click();
    cy.get('#input-1550').type('QA TEST 2');
    cy.get('#input-1552').click();
    cy.get('#v-menu-1554 div:nth-child(7) div.v-list-item-title').click();
    cy.get('#input-1555').click();
    cy.get('#input-1555').type('656664432');
    cy.get('#app button.v-btn--variant-tonal').click();
    cy.get('#app button.v-btn--variant-tonal span.v-btn__content').click();
    cy.get('#input-1625').click();
    cy.get('#v-menu-1627 div:nth-child(3) div.v-list-item__content div.v-list-item-title').click();
    cy.get('#input-1628').click();
    cy.get('#input-1628').type('QA TEST');
    cy.get('#input-1630').click();
    cy.get('#input-1632').click();
    cy.get('#v-menu-1634 div:nth-child(2) > div.v-list-item__content > div.v-list-item-title').click();
    cy.get('#input-1635').click();
    cy.get('#input-1635').type('UBA');
    cy.get('#app button.v-btn--variant-tonal span.v-btn__content').click();
    cy.get('#input-1730').click();
    cy.get('#input-1732').click();
    cy.get('#input-1734').click();
    cy.get('#app button.v-btn--size-default.v-btn--variant-tonal span.v-btn__content').click();
    cy.get('#input-1788').check();
    cy.get('#input-1793').check();
    cy.get('#input-1795').click();
    cy.get('#input-1795').type('12092');
    cy.get('#input-1797').click();
    cy.get('#input-1797').type('12092');
    cy.get('#app div.v-stepper-window-item.v-window-item--active div.justify-end.v-card-actions button.v-btn').click();
  })
})