describe('template spec', () => {
  it('passes', () => {
    cy.visit('https://africx-admin-test.afric.group/auth/login')
    cy.get('[name="username"]').click();
    cy.get('[name="username"]').type('sibpro61+13@gmail.com');
    cy.get('#input-2').click();
    cy.get('#input-2').type('12092');
    cy.get('#checkbox-4').check();
    cy.get('#app button.v-btn').click();
    cy.get('#app a.bg-primary span.v-btn__content').click();
    cy.get('#v-list-group--id-Symbol\\(68\\) div.mr-auto').click();
    cy.get('#app a[href="/corporateaccount"] div.v-list-item-title').click();
    cy.get('#app button.bg-primary').click();
    cy.get('#app button.bg-primary span.v-btn__content').click();
    cy.get('#v-menu-177 div:nth-child(1) > div.v-list-item__content > div.v-list-item-title').click();
    cy.get('#input-521').click();
    cy.get('#input-521').click();
    cy.get('#app div.v-field__input').click();
    cy.get('#v-menu-527 div:nth-child(7) div.v-list-item-title').click();
    cy.get('#input-521').click();
    cy.get('#input-521').type('678989900');
    cy.get('#input-523').click();
    cy.get('#app div:nth-child(4) div:nth-child(1) div.v-row').click();
    cy.get('#input-523').type('qabanktest@gmail.com');
    cy.get('#app button.v-btn--variant-tonal span.v-btn__content').click();
    cy.get('#input-578').click();
    cy.get('#input-578').type('qa ');
    cy.get('#input-580').click();
    cy.get('#input-578').click();
    cy.get('#input-578').type('corpoarte');
    cy.get('#input-580').click();
    cy.get('#input-580').type('qa');
    cy.get('#input-582').click();
    cy.get('#input-582').type('qa test corp');
    cy.get('#input-584').click();
    cy.get('#input-584').type('reel');
    cy.get('#input-586').click();
    cy.get('#v-menu-588 div:nth-child(3) div.v-list-item-title').click();
    cy.get('#input-589').click();
    cy.get('#input-589').type('655509087');
    cy.get('#input-591').click();
    cy.get('#input-591').type('corporatebank@gmail.com');
    cy.get('#input-597').click();
    cy.get('#input-597').type('false');
    cy.get('#app button.v-btn--variant-tonal span.v-btn__content').click();
    cy.get('#input-631').click();
    cy.get('#v-menu-633 button.text-primary span.v-btn__content').click();
    cy.get('#input-634').click();
    cy.get('#v-menu-636 div:nth-child(7) div.v-list-item-title').click();
    cy.get('#input-637').click();
    cy.get('#v-menu-639 div:nth-child(6) div.v-list-item-title').click();
    cy.get('#input-640').click();
    cy.get('#input-640').type('Douala');
    cy.get('#input-642').click();
    cy.get('#input-642').type('Akwa');
    cy.get('#input-644').click();
    cy.get('#input-644').type('2434342');
    cy.get('#input-646').click();
    cy.get('#input-646').type('324324');
    cy.get('#input-648').click();
    cy.get('#input-648').type('34354');
    cy.get('#app button.v-btn--variant-tonal').click();
    cy.get('#input-734').click();
    cy.get('#input-734').type('DLA-6');
    cy.get('#input-736').click();
    cy.get('#input-736').type('FD454646546');
    cy.get('#input-738').click();
    cy.get('#input-738').type('PO7874534534');
    cy.get('#input-740').click();
    cy.get('#app div[aria-owns="v-menu-744"] div.v-field__input').click();
    cy.get('#v-menu-744 div:nth-child(4) div.v-list-item__content div.v-list-item-title').click();
    cy.get('#input-745').click();
    cy.get('#input-745').type('QA TESTFGGFG');
    cy.get('#app div.v-field--focused div.v-field__input').click();
    cy.get('#v-menu-754 div:nth-child(12) div.v-list-item-title').click();
    cy.get('#app button.v-btn--size-default.v-btn--variant-tonal span.v-btn__content').click();
    cy.get('#input-802').click();
    cy.get('#v-menu-804 div:nth-child(3) div.v-list-item__content div.v-list-item-title').click();
    cy.get('#input-805').click();
    cy.get('#v-menu-807 div:nth-child(2) > div.v-list-item__content > div.v-list-item-title').click();
    cy.get('#input-808').click();
    cy.get('#input-808').type('QA TESTFGF');
    cy.get('#app div.v-field--focused div.v-field__input').click();
    cy.get('#v-menu-812 div:nth-child(2) > div.v-list-item__content > div.v-list-item-title').click();
    cy.get('#input-813').click();
    cy.get('#input-813').type('QA TEST');
    cy.get('#input-818').click();
    cy.get('#input-818').type('UBA');
    cy.get('#input-823').click();
    cy.get('#v-menu-825 div:nth-child(2) > div.v-list-item__content > div.v-list-item-title').click();
    cy.get('#app button.v-btn--variant-tonal').click();
    cy.get('#input-935').click();
    cy.get('#v-menu-937 div:nth-child(8) div.v-list-item-title').click();
    cy.get('#input-964').click();
    cy.get('#input-966').click();
    cy.get('#app button.v-btn--size-default.v-btn--variant-tonal').click();
    cy.get('#input-982').click();
    cy.get('#v-menu-984 div:nth-child(2) > div.v-list-item__content > div.v-list-item-title').click();
    cy.get('#app div.v-stepper-window-item.v-window-item--active > form.v-form > div.bg-gray100 > div:nth-child(4)').click();
    cy.get('#app button.v-btn--variant-tonal span.v-btn__content').click();
    cy.get('#input-1014').click();
    cy.get('#v-menu-1016 div:nth-child(2) > div.v-list-item__content > div.v-list-item-title').click();
    cy.get('#input-1017').click();
    cy.get('#input-1017').type('QA TEST');
    cy.get('#input-1019').click();
    cy.get('#input-1019').type('BANK');
    cy.get('#input-1021').click();
    cy.get('#v-menu-1023 div:nth-child(3) div.v-list-item__content div.v-list-item-title').click();
    cy.get('#input-1024').click();
    cy.get('#v-menu-1026 div:nth-child(2) > div.v-list-item__content > div.v-list-item-title').click();
    cy.get('#app button.v-btn--variant-tonal span.v-btn__content').click();
    cy.get('#input-1057').click();
    cy.get('#v-menu-1059 button.text-primary span.v-btn__content').click();
    cy.get('#input-1057').click();
    cy.get('#v-menu-1059 button.v-btn--density-comfortable svg.v-icon__svg').click();
    cy.get('#v-menu-1059 button:nth-child(59) span.v-btn__content').click();
    cy.get('#v-menu-1059 div:nth-child(25) span.v-btn__content').click();
    cy.get('#input-1060').click();
    cy.get('#input-1060').type('DOUALA');
    cy.get('#input-1062').click();
    cy.get('#v-menu-1064 div:nth-child(7) div.v-list-item-title').click();
    cy.get('#input-1065').click();
    cy.get('#input-1065').type('QA TEST');
    cy.get('#app button.v-btn--variant-tonal span.v-btn__content').click();
    cy.get('#input-1304').click();
    cy.get('#v-menu-1306 div:nth-child(7) div.v-list-item-title').click();
    cy.get('#input-1307').click();
    cy.get('#v-menu-1309 div:nth-child(6) div.v-list-item-title').click();
    cy.get('#input-1310').click();
    cy.get('#input-1310').type('DOUALA');
    cy.get('#input-1312').click();
    cy.get('#input-1312').type('AKWA');
    cy.get('#input-1314').click();
    cy.get('#input-1314').type('2233543');
    cy.get('#input-1316').click();
    cy.get('#input-1316').type('3443432');
    cy.get('#input-1318').click();
    cy.get('#input-1318').type('23343');
    cy.get('#app button.v-btn--variant-tonal').click();
    cy.get('#input-1371').click();
    cy.get('#v-menu-1373 div:nth-child(2)').click();
    cy.get('#input-1374').click();
    cy.get('#input-1374').type('PER34352');
    cy.get('#input-1376').click();
    cy.get('#input-1376').type('PO9845864735');
    cy.get('#input-1378').click();
    cy.get('#v-menu-1380 button.text-primary').click();
    cy.get('#input-1381').click();
    cy.get('#input-1381').type('DOUALA');
    cy.get('#input-1383').click();
    cy.get('#v-menu-1385 button.v-btn--density-comfortable svg.v-icon__svg').click();
    cy.get('#v-menu-1385 button:nth-child(110) span.v-btn__content').click();
    cy.get('#v-menu-1385 div:nth-child(39) span.v-btn__content').click();
    cy.get('#app button.v-btn--variant-tonal').click();
    cy.get('#input-1659').click();
    cy.get('#input-1661').click();
    cy.get('#input-1663').click();
    cy.get('#input-1665').click();
    cy.get('#app button.v-btn--size-default.v-btn--variant-tonal').click();
    cy.get('#input-1719').check();
    cy.get('#input-1724').check();
    cy.get('#input-1726').click();
    cy.get('#input-1726').type('12092');
    cy.get('#input-1728').click();
    cy.get('#input-1728').type('12092');
    cy.get('#app div.v-stepper-window-item.v-window-item--active div.justify-end.v-card-actions button.v-btn span.v-btn__prepend i.notranslate svg.v-icon__svg').click();
  })
})