describe('template spec', () => {
  it('passes', () => {
    cy.visit('https://africx-admin-test.afric.group/auth/login')
    cy.get('[name="username"]').click();
    cy.get('[name="username"]').type('sibpro61+13@gmail.com');
    cy.get('#input-2').click();
    cy.get('#input-2').type('12092');
    cy.get('#checkbox-4').check();
    cy.get('#app button.v-btn').click();
    cy.get('#app a.bg-primary span.v-btn__content').click();
    cy.get('#v-list-group--id-Symbol\\(68\\) div.mr-auto').click();
    cy.get('#app a[href="/corporateaccount"] div.v-list-item-title').click();
    cy.get('#app button.bg-primary').click();
    cy.get('#app button.bg-primary span.v-btn__content').click();
    cy.get('#v-menu-177 div:nth-child(2) > div.v-list-item__content > div.v-list-item-title').click();
    cy.get('#input-464').click();
    cy.get('#app div:nth-child(4) > div:nth-child(1) > div.v-row > div:nth-child(1)').click();
    cy.get('#input-464').click();
    cy.get('#input-468').click();
    cy.get('#v-menu-470 div:nth-child(7) div.v-list-item-title').click();
    cy.get('#input-464').click();
    cy.get('#input-464').type('677809055');
    cy.get('#input-466').click();
    cy.get('#input-466').type('qatestpay@gmail.com');
    cy.get('#app button.v-btn--variant-tonal span.v-btn__content').click();
    cy.get('#input-521').click();
    cy.get('#input-521').type('QSASAS');
    cy.get('#input-523').click();
    cy.get('#input-523').type('ASAS');
    cy.get('#input-525').click();
    cy.get('#input-525').type('ASAS');
    cy.get('#input-527').click();
    cy.get('#input-527').type('REEL');
    cy.get('#input-529').click();
    cy.get('#v-menu-531 div:nth-child(3) div.v-list-item-title').click();
    cy.get('#input-532').click();
    cy.get('#input-532').type('655432122');
    cy.get('#input-534').click();
    cy.get('#input-534').type('corpo@gemail.com');
    cy.get('#input-540').click();
    cy.get('#input-540').type('false');
    cy.get('#app button.v-btn--variant-tonal span.v-btn__content').click();
    cy.get('#input-574').click();
    cy.get('#v-menu-576 button.text-primary').click();
    cy.get('#input-577').click();
    cy.get('#v-menu-579 div:nth-child(7) div.v-list-item-title').click();
    cy.get('#app div.v-field--focused div.v-field__input').click();
    cy.get('#v-menu-582 div:nth-child(6) p').click();
    cy.get('#input-583').click();
    cy.get('#input-583').type('Douala');
    cy.get('#input-585').click();
    cy.get('#input-585').type('Akwa');
    cy.get('#input-587').click();
    cy.get('#input-587').type('23355787');
    cy.get('#input-589').click();
    cy.get('#input-589').type('324354');
    cy.get('#input-591').click();
    cy.get('#input-591').type('3454544');
    cy.get('#app button.v-btn--variant-tonal span.v-btn__content').click();
    cy.get('#input-676').click();
    cy.get('#input-676').type('DLA-5');
    cy.get('#input-678').click();
    cy.get('#input-678').type('PRF97923839');
    cy.get('#input-680').click();
    cy.get('#input-680').type('439I38R7834R');
    cy.get('#input-682').click();
    cy.get('#input-684').click();
    cy.get('#v-menu-686 div:nth-child(4) div.v-list-item__content div.v-list-item-title').click();
    cy.get('#input-687').click();
    cy.get('#input-687').type('QA TEST');
    cy.get('#input-694').click();
    cy.get('#v-menu-696 div:nth-child(13) p').click();
    cy.get('#app div.v-stepper-actions').click();
    cy.get('#app button.v-btn--size-default.v-btn--variant-tonal').click();
    cy.get('#input-744').click();
    cy.get('#v-menu-746 div:nth-child(3) div.v-list-item__content div.v-list-item-title').click();
    cy.get('#input-747').click();
    cy.get('#v-menu-749 div:nth-child(2) > div.v-list-item__content > div.v-list-item-title').click();
    cy.get('#input-750').click();
    cy.get('#input-750').type('Marc Ndoua');
    cy.get('#input-752').click();
    cy.get('#v-menu-754 div:nth-child(2) > div.v-list-item__content > div.v-list-item-title').click();
    cy.get('#input-755').click();
    cy.get('#input-755').type('QA TEEST');
    cy.get('#input-760').click();
    cy.get('#input-760').type('UBA');
    cy.get('#input-763').click();
    cy.get('#input-765').click();
    cy.get('#v-menu-767 div:nth-child(2) > div.v-list-item__content > div.v-list-item-title').click();
    cy.get('#app button.v-btn--variant-tonal span.v-btn__content').click();
    cy.get('#app div[aria-owns="v-menu-885"] div.v-field__input').click();
    cy.get('#v-menu-885 div:nth-child(5) div.v-list-item-title').click();
    cy.get('#app div.v-field--focused div.v-field__input').click();
    cy.get('#v-menu-885 div:nth-child(7) div.v-list-item-title').click();
    cy.get('#input-883').click();
    cy.get('#v-menu-885 div:nth-child(8) div.v-list-item-title').click();
    cy.get('#app div.v-stepper-window-item.v-window-item--active > form.v-form > div.bg-gray100 > div:nth-child(4)').click();
    cy.get('#input-912').click();
    cy.get('#input-914').click();
    cy.get('#app button.v-btn--size-default.v-btn--variant-tonal').click();
    cy.get('#input-952').click();
    cy.get('#v-menu-954 div:nth-child(2) > div.v-list-item__content > div.v-list-item-title').click();
    cy.get('#app div.v-stepper-window-item.v-window-item--active > form.v-form > div.bg-gray100 > div:nth-child(4)').click();
    cy.get('#app button.v-btn--variant-tonal span.v-btn__content').click();
    cy.get('#input-984').click();
    cy.get('#v-menu-986 div:nth-child(2) > div.v-list-item__content > div.v-list-item-title').click();
    cy.get('#input-987').click();
    cy.get('#input-987').type('QA TEST');
    cy.get('#input-989').click();
    cy.get('#input-989').type('QA TEST');
    cy.get('#input-991').click();
    cy.get('#v-menu-993 div:nth-child(3) div.v-list-item__content div.v-list-item-title').click();
    cy.get('#input-994').click();
    cy.get('#v-menu-996 div:nth-child(2) > div.v-list-item__content > div.v-list-item-title').click();
    cy.get('#app button.v-btn--variant-tonal').click();
    cy.get('#input-1027').click();
    cy.get('#v-menu-1029 path[d="M7,10L12,15L17,10H7Z"]').click();
    cy.get('#v-menu-1029 button:nth-child(5) span.v-btn__content').click();
    cy.get('#v-menu-1029 button.v-btn--density-comfortable').click();
    cy.get('#v-menu-1029 button:nth-child(26)').click();
    cy.get('#v-menu-1029 div:nth-child(32) span.v-btn__content').click();
    cy.get('#input-1030').click();
    cy.get('#input-1030').type('DOUALA');
    cy.get('#input-1032').click();
    cy.get('#v-menu-1034 div:nth-child(7) div.v-list-item-title').click();
    cy.get('#input-1035').click();
    cy.get('#input-1035').type('QA TEST');
    cy.get('#app button.v-btn--variant-tonal').click();
    cy.get('#app div[aria-owns="v-menu-1373"] div.v-field__input').click();
    cy.get('#v-menu-1373 div:nth-child(7) div.v-list-item-title').click();
    cy.get('#input-1374').click();
    cy.get('#v-menu-1376 div:nth-child(6) div.v-list-item-title').click();
    cy.get('#input-1377').click();
    cy.get('#input-1377').type('QA TEST');
    cy.get('#input-1379').click();
    cy.get('#input-1379').click();
    cy.get('#input-1379').type('AKWA');
    cy.get('#input-1381').click();
    cy.get('#input-1381').type('095473');
    cy.get('#input-1383').click();
    cy.get('#input-1383').type('23545');
    cy.get('#input-1385').click();
    cy.get('#input-1385').type('323223');
    cy.get('#app button.v-btn--variant-tonal').click();
    cy.get('#app div[aria-owns="v-menu-1440"] div.v-field__input').click();
    cy.get('#v-menu-1440 div:nth-child(2) > div.v-list-item__content > div.v-list-item-title').click();
    cy.get('#input-1441').click();
    cy.get('#input-1441').click();
    cy.get('#input-1441').type('P3454DFVCV');
    cy.get('#input-1443').click();
    cy.get('#input-1443').type('PO45R435DERE');
    cy.get('#input-1445').click();
    cy.get('#v-menu-1447 button.v-btn--density-comfortable svg.v-icon__svg').click();
    cy.get('#v-menu-1447 button.bg-primary span.v-btn__content').click();
    cy.get('#v-menu-1447 button.text-primary span.v-btn__content').click();
    cy.get('#input-1448').click();
    cy.get('#input-1448').type('DOUALA');
    cy.get('#input-1450').click();
    cy.get('#v-menu-1452 button.v-btn--density-comfortable svg.v-icon__svg').click();
    cy.get('#v-menu-1452 button:nth-child(110)').click();
    cy.get('#v-menu-1452 div:nth-child(32) button.v-btn').click();
    cy.get('#app button.v-btn--variant-tonal').click();
    cy.get('#input-1857').click();
    cy.get('#input-1859').click();
    cy.get('#input-1861').click();
    cy.get('#input-1863').click();
    cy.get('#app button.v-btn--size-default.v-btn--variant-tonal').click();
    cy.get('#input-1917').check();
    cy.get('#input-1922').check();
    cy.get('#input-1924').click();
    cy.get('#input-1924').type('12092');
    cy.get('#input-1926').click();
    cy.get('#input-1926').type('12092');
    cy.get('#app div.v-stepper-window-item.v-window-item--active div.justify-end.v-card-actions button.v-btn span.v-btn__content').click();
  })
})